### ISSUE TITLE
Incorrect processing of double curly brackets

### ISSUE THREAD

**Issue by stdstring** [Wissance/stringFormatter#6]
In C#, the following code `System.String.Format("{0} = {{0}}", "iddqd")` gives us the following result: `"iddqd = {0}"`. But this realization of **stringFormatter** module for call `stringFormatter.Format("{0} = {{0}}", "iddqd")` gives us the following result: `"iddqd = {iddqd}"`, which is wrong

**Comment by EvilLord666** [comment]
Done, available in release 1.0
